//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zp_osmanabad_api.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("zp_osmanabad_api.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed GetAllData Successfully.
        /// </summary>
        public static string Completed_GetAllData_Successfully
        {
            get
            {
                return ResourceManager.GetString("Completed_GetAllData_Successfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed GetAllDataById Successfully.
        /// </summary>
        public static string Completed_GetAllDataById_Successfully
        {
            get
            {
                return ResourceManager.GetString("Completed_GetAllDataById_Successfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Deleted Successfully.
        /// </summary>
        public static string Data_Deleted_Successfully
        {
            get
            {
                return ResourceManager.GetString("Data_Deleted_Successfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Save Successfully.
        /// </summary>
        public static string Data_Save_Successfully
        {
            get
            {
                return ResourceManager.GetString("Data_Save_Successfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Update Successfully.
        /// </summary>
        public static string Data_Update_Successfully
        {
            get
            {
                return ResourceManager.GetString("Data_Update_Successfully", resourceCulture);
            }
        }
    }
}